[package]
edition = "2021"
name = "compress-rs"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
brotli = "7.0.0"
flate2 = "1.0.34"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2", features = ["async"] }
napi-derive = "2.12.2"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
strip = "symbols"
