/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Algorithm {
  Gzip = 'Gzip',
  BrotliCompress = 'BrotliCompress',
  Deflate = 'Deflate',
  DeflateRaw = 'DeflateRaw'
}
export interface CompressionOptions {
  level?: number
}
export declare function getCompressionOptions(algorithm: Algorithm, compressionOptions: CompressionOptions): CompressionOptions
export declare function compress(content: Buffer, algorithm: Algorithm, options: CompressionOptions): Promise<Buffer>
